<?php require('template/header.phtml') ?>
    <!--MAIN CONTENT-->
    <div class="container dashboard">
        <h3>Dashboard - Coming Soon™</h3>
    </div>
    <footer class="footer elegant-color-dark">
        <div class="container">
            <span class="text-muted">TimingTower [Pre-release Version] | © Charlie Burgess 2020</span>
        </div>
    </footer>
    <!--MAIN CONTENT-->
<?php require('template/footer.phtml') ?>