<?php require('template/header.phtml') ?>
    <!--MAIN CONTENT-->
    <table class="table table-borderless timing-dark-color white-text ttHeaderLeaderboard">
        <tr>
            <!--DRIVER 1-->
            <th rowspan="2" class="vertLarge align-middle">1</th>
            <th class="" colspan="3">HAMILTON</th>
            <!--DRIVER 1-->
            <!--DRIVER 2-->
            <th rowspan="2" class="vertLarge align-middle">2</th>
            <th class="" colspan="3">LECLERC</th>
            <!--DRIVER 2-->
            <!--DRIVER 3-->
            <th rowspan="2" class="vertLarge align-middle">3</th>
            <th class="" colspan="3">NORRIS</th>
            <!--DRIVER 3-->
            <!--DRIVER 4-->
            <th rowspan="2" class="vertLarge align-middle">4</th>
            <th class="" colspan="3">RICCIARDO</th>
            <!--DRIVER 4-->
            <!--DRIVER 5-->
            <th rowspan="2" class="vertLarge align-middle">5</th>
            <th class="" colspan="3">VERSTAPPEN</th>
            <!--DRIVER 5-->
        </tr>
        <tr>
            <th class="teamTurqBG">#44</th>
            <th class="">Mercedes</th>
            <th class="">1:19.592</th>

            <th class="teamRedBG">#16</th>
            <th class="">Ferrari</th>
            <th class="">1:19.902</th>

            <th class="teamOrangeBG">#4</th>
            <th class="">McLaren</th>
            <th class="">1:20.527</th>

            <th class="teamYellowBG">#3</th>
            <th class="">Renault</th>
            <th class="">1:21.375</th>

            <th class="teamDarkBlueBG">#33</th>
            <th class="">Red Bull</th>
            <th class="">1:22.375</th>
        </tr>
    </table>
    <!--MAIN CONTENT-->
<?php require('template/footer.phtml') ?>