<?php require('template/header.phtml') ?>
    <!--MAIN CONTENT-->
    <!-- AJAX Script to fresh tower every 3 seconds -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        $(document).ready(function ()
        {
            setInterval(function () {
                $("#verticalMainRow").load("tickerRefresh.php");
            },3000);
        });
    </script>
    <!-- AJAX Script to fresh tower every 3 seconds -->
    <table class="table table-borderless timing-dark-color white-text ttHeaderLeaderboard" id="verticalMainRow">
        <!--<tr id="">
        </tr>-->
        <!--<tr>
            <th class="teamTurqBG">#44</th>
            <th class="">Mercedes</th>
            <th class="">1:19.592</th>

            <th class="teamRedBG">#16</th>
            <th class="">Ferrari</th>
            <th class="">1:19.902</th>

            <th class="teamOrangeBG">#4</th>
            <th class="">McLaren</th>
            <th class="">1:20.527</th>

            <th class="teamYellowBG">#3</th>
            <th class="">Renault</th>
            <th class="">1:21.375</th>

            <th class="teamDarkBlueBG">#33</th>
            <th class="">Red Bull</th>
            <th class="">1:22.375</th>
        </tr>-->
    </table>
    <!--MAIN CONTENT-->
<?php require('template/footer.phtml') ?>