<?php require('template/header.phtml') ?>

    <!--MAIN CONTENT-->
    <!--Main Timing Tower-->
    <div class="banner-container animated fadeIn">
        <div class="banner-col banner-col-3">RACE CONTROL</div>
        <div class="banner-col banner-col-6">All cars must return to the pitlane (LAP 25)</div>
    </div>
    <!--Main Timing Tower-->
    <!--MAIN CONTENT-->
<?php require('template/footer.phtml') ?>