<?php require('template/header.phtml') ?>

    <!--MAIN CONTENT-->
                <!--Main Timing Tower-->

                <?php
                    /* First time the page loads, we need to get set the last
                       Db change date/time to now, otherwise data will not load */
                    $_SESSION['dbChange'] = date('Y-m-d H:i:s');
                ?>

                <!-- AJAX Script to fresh tower every second -->
                <!-- Performance wise this is bad as we are requesting the data once a second even if nothing
                has changed, should be okay for 20 drivers, but the more you add its going to increase cpu time -->
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
                <script>
                    $(document).ready(function ()
                    {
                       setInterval(function () {
                           $("#towerReloadElement").load("towerRefresh.php");
                       },1000);
                    });
                </script>
                <!--<script>
                    $(document).ready(function ()
                    {
                       setInterval(function () {
                           $("#flagReloadElement").load("eventRefresh.php");
                       },1000);
                    });
                </script>-->
                <!-- AJAX Script to fresh tower every second -->


                <table class="table table-borderless timing-dark-color white-text ttCustomTable">
                    <!-- SESSION INFO -->
                    <thead>
                    <!-- Session Name/Laps/Timers -->
                    <tr>
                        <th colspan="100%" id="ttBranding">LAPS</th>
                    </tr>
                    <tr>
                        <th colspan="100%" id="ttBranding">55/78</th>
                    </tr>

                    <!-- Session Name/Laps/Timers -->
                    <!-- Flags/Warnings, only show 1 at a time! -->
                    <div id="flagReloadElement">

                    </div>
                    <!--<tr class="redFlag">
                        <th colspan="100%" id="ttBranding"><i class="fas fa-flag"></i></th>
                    </tr>-->
                    <!--<tr class="yellowFlag">
                        <th colspan="100%" id="ttBranding"><i class="fas fa-flag"></i></th>
                    </tr>-->
                    <tr class="greenFlag">
                        <th colspan="100%" id="ttBranding"><i class="fas fa-flag"></i></th>
                    </tr>
                    <!--<tr class="">
                        <th colspan="100%" id="ttBranding"><i class="fas fa-flag-checkered"></i></th>
                    </tr>-->
                    <!-- Flags/Warnings, only show 1 at a time! -->
                    </thead>
                    <!-- SESSION INFO -->
                    <tbody id="towerReloadElement">
                    </tbody>
                </table>
                <!--Main Timing Tower-->
    <!--MAIN CONTENT-->
<?php require('template/footer.phtml') ?>