<?php require('template/header.phtml') ?>
    <!-- TEMPORARY PAGE REFRESH EVERY X SEONDS -->
    <!--<meta http-equiv="refresh" content="5">-->
    <!-- TEMPORARY PAGE REFRESH EVERY X SEONDS -->

    <!--MAIN CONTENT-->
                <!--Main Timing Tower-->
                <table class="table table-borderless timing-dark-color white-text ttCustomTable">
                    <!-- SESSION INFO -->
                    <thead>
                    <!-- Session Name/Laps/Timers -->
                    <tr>
                        <th colspan="100%" id="ttBranding">LAPS</th>
                    </tr>
                    <tr>
                        <th colspan="100%" id="ttBranding">55/78</th>
                    </tr>
                    <!-- Session Name/Laps/Timers -->

                    <!-- Flags/Warnings, only show 1 at a time! -->
                    <!--<tr class="redFlag">
                        <th colspan="100%" id="ttBranding"><i class="fas fa-flag"></i></th>
                    </tr>-->
                    <tr class="yellowFlag">
                        <th colspan="100%" id="ttBranding"><i class="fas fa-flag"></i> SECTOR 1</th>
                    </tr>
                    <!--<tr class="greenFlag">
                        <th colspan="100%" id="ttBranding"><i class="fas fa-flag"></i></th>
                    </tr>-->
                    <!--<tr class="">
                        <th colspan="100%" id="ttBranding"><i class="fas fa-flag-checkered"></i></th>
                    </tr>-->
                    <!-- Flags/Warnings, only show 1 at a time! -->
                    </thead>
                    <!-- SESSION INFO -->
                    <tbody>
                    <?php
                    $position = 1;
                    $teamClass = "teamUnknown";
                    foreach ($view->driverDataSet as $driverData) {
                        if($position==1)
                            echo '<tr class="fastestLapHighlight">';
                        else
                            echo '<tr class="">';
                        echo '<td><span>' . $position .'</span></td>';
                        /*Get the required team colour - probably a much easier way of doing this? */
                        /*switch ($driverData->getDriverTeam()) {
                            case "mercedes":
                                $teamClass = "teamTurq";
                                break;
                            case "redbull":
                                $teamClass = "teamDarkBlue";
                                break;
                            case "ferrari":
                                $teamClass = "teamRed";
                                break;
                            case "alphatauri":
                                $teamClass = "teamWhite";
                                break;
                            case "alfaromeo":
                                $teamClass = "teamDarkRed";
                                break;
                            case "mclaren":
                                $teamClass = "teamOrange";
                                break;
                            case "racingpoint":
                                $teamClass = "teamPink";
                                break;
                            case "williams":
                                $teamClass = "teamLightBlue";
                                break;
                            case "haas":
                                $teamClass = "teamGold";
                                break;
                            case "renault":
                                $teamClass = "teamYellow";
                                break;
                            default:
                                $teamClass = "teamUnknown";
                                break;
                        }*/
                        /*Get the required team colour - probably a much easier way of doing this? */
                        echo '<td class="">' . $driverData->getDriverAbv() . '</td>';
                        echo '<td class="lapTimeCollapse">1:26.598</td>';
                        echo '</tr>';
                        $position = $position +1;
                    }
                    ?>
                    </tbody>
                </table>
                <!--Main Timing Tower-->
    <!--MAIN CONTENT-->
<?php require('template/footer.phtml') ?>