<?php require('template/header.phtml') ?>
    <!--MAIN CONTENT-->
    <!-- AJAX Script to fresh tower every 3 seconds -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
        $(document).ready(function ()
        {
            setInterval(function () {
                $("#verticalMainRow").load("tickerRefresh.php");
            },3000);
        });
    </script>
    <!-- AJAX Script to fresh tower every 3 seconds -->
    <table class="table table-borderless timing-dark-color white-text ttHeaderLeaderboard" id="verticalMainRow">
    </table>
    <!--MAIN CONTENT-->
<?php require('template/footer.phtml') ?>